# Generated by Django 2.0 on 2021-04-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='Enter name of the task', max_length=30, verbose_name='Task name')),
                ('task_description', models.TextField(help_text='Add task description', max_length=200, verbose_name='Task description')),
                ('status', models.CharField(choices=[('i', 'Initial'), ('p', 'Pending'), ('r', 'Resolved')], default='i', help_text='Set status of the task', max_length=1)),
                ('deadline_date', models.DateTimeField(verbose_name='Task deadline date')),
            ],
        ),
    ]
