# Generated by Django 2.0 on 2021-04-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline_date',
        ),
    ]
